# Generated by Django 5.0.6 on 2024-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="books",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
