# Generated by Django 5.0.6 on 2024-06-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="books",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
